Update FAQ for Newer Django Versions
django-userena-ce/django-userena-ce pull request #40
Opened 2018-11-13 16:58 UTC by WisChrendel

Updated the "Hackery" to move the new fields to the front of the OrderedDict with move_to_end('key', last=False).

Updated user_profile = new_user.get_profile() to user_profile = new_user.my_profile. get_profile() has been deprecated.

2018-11-13 18:03 UTC, jmsmkn requested changes
Thanks! Looks good, but I don't think the import of MyProfile is needed, could you confirm?

2018-11-13 18:03 UTC, jmsmkn commented on docs/faq.rst
> +    from .models import MyProfile
```suggestion
```

I do not think this import is necessary

2018-11-13 19:08 UTC, WisChrendel commented on docs/faq.rst
> +    from .models import MyProfile
Yes you are correct

2018-11-14 09:22 UTC, merged

2018-11-14 09:22 UTC, jmsmkn commented
Thank you for your contribution!